- name: Upgrading packages in the nodes
  hosts: all
  tasks:
    - name: Upgrade packages
      apt:
        force_apt_get: yes
        upgrade: dist
      become: yes
      become_method: sudo

- name: Installing packages in the nodes
  hosts: all
  tasks:
    - name: Install packages
      apt:
        pkg:
          - vim
          - build-essential
          - screen
          - curl
          - wget
          - git
          - python3
          - python3-pip
          - mpich
          - iputils-ping
          - munge
        state: latest
        update_cache: true

- name: Generate SSH key pairs
  hosts: all
  tasks:
    - openssh_keypair:
        path: ~/.ssh/id_rsa
      register: keypair

    - fetch:
        src: ~/.ssh/id_rsa.pub
        dest: public_keys

- name: Aggregate public keys into a single file
  hosts: localhost
  tasks:
    - command:
        cmd: bash -c "cat ~/.ssh/id_rsa.pub > authorized_keys && cat $(find . -name *.pub) >> authorized_keys"

- name: Copy public keys to the nodes so they can talk to each other
  hosts: all
  tasks:
    - copy:
        src: authorized_keys
        dest: ~/.ssh
        owner: root
        group: root
        mode: 0664

- name: Add trusted connections to the known_hosts file in all the nodes
  hosts: all
  tasks:
    - copy:
        src: ../infrastructure/.nodes_ips.dat
        dest: ~/
        owner: root
        group: root
        mode: 0664

    - command:
        cmd: bash -c "for node_ip in $(cat .nodes_ips.dat); do ssh -o StrictHostKeyChecking=no root@${node_ip} echo 'Connected'; done;"

    - file:
        path: ~/.nodes_ips.dat
        state: absent

- name: Get a reference MUNGE key taken from the head node
  hosts: head
  tasks:
    - fetch:
        src: /etc/munge/munge.key
        dest: munge
      register: munge

- name: Copy reference MUNGE key to all the nodes
  hosts: all
  tasks:
    - copy:
        src: "{{ hostvars[groups.head[0]].munge.dest }}"
        dest: /etc/munge
        owner: munge
        group: munge
        mode: 0600

- name: Start the MUNGE daemon
  hosts: all
  tasks:
    - command:
        cmd: bash -c "/etc/init.d/munge stop && /etc/init.d/munge start"
