# Ubuntu packages

- name: Upgrading packages in the nodes
  hosts: all
  tasks:
    - name: Upgrade packages
      apt:
        force_apt_get: yes
        upgrade: dist
      become: yes
      become_method: sudo

- name: Installing packages in the nodes
  hosts: all
  tasks:
    - name: Install packages
      apt:
        pkg:
          - vim
          - build-essential
          - screen
          - curl
          - wget
          - git
          - python3
          - python3-pip
          - iputils-ping
          - munge
        state: latest
        update_cache: true

# DNS with node names

- name: Get IPs of the nodes and build DNS
  hosts: localhost
  tasks:
    - command:
        cmd: bash -c "head -n 1 ../infrastructure/.nodes_ips.dat"
      register: head_ip

    - command:
        cmd: bash -c "sed 1d ../infrastructure/.nodes_ips.dat"
      register: compute_ips

    - command:
        cmd: bash -c "seq 0 $(wc -l ../infrastructure/.nodes_ips.dat | awk '{ print $1 - 1 }')"
      register: compute_indices

- name: Update hosts file
  hosts: all
  vars:
    head_ip: "{{ hostvars['localhost'].head_ip.stdout }}"
    compute_ips: "{{ hostvars['localhost'].compute_ips.stdout | split }}"
    compute_indices: "{{ hostvars['localhost'].compute_indices.stdout | split }}"
  tasks:
    - command:
        cmd: bash -c "echo '{{ head_ip }}      head' >> /etc/hosts"

    - command:
        cmd: bash -c "echo '{{ item[1] }}      compute-{{ item[0] }}' >> /etc/hosts"
      loop: "{{ compute_indices | zip(compute_ips) }}"
